/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IU;

import java.awt.Dimension;

/**
 *
 * @author oscar
 */
public class FrmMenuRentaCar extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuRentaCar
     */
    public FrmMenuRentaCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmListaCliente = new javax.swing.JInternalFrame();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        frmRegistroCliente = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardarCliente = new javax.swing.JButton();
        btnCerrarCliente = new javax.swing.JButton();
        frmListaLicenciaConducir = new javax.swing.JInternalFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        frmRegistroLicenciaConducir = new javax.swing.JInternalFrame();
        frmListaMetodoPago = new javax.swing.JInternalFrame();
        frmRegistroMetodoPago = new javax.swing.JInternalFrame();
        frmListaTarifa = new javax.swing.JInternalFrame();
        frmRegistroTarifa = new javax.swing.JInternalFrame();
        frmListaVehiculo = new javax.swing.JInternalFrame();
        frmRegistroVehiculo = new javax.swing.JInternalFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuCliente = new javax.swing.JMenuItem();
        mnuLicenciaConducir = new javax.swing.JMenuItem();
        mnuMetodoPago = new javax.swing.JMenuItem();
        mnuTarifa = new javax.swing.JMenuItem();
        mnuVehiculo = new javax.swing.JMenuItem();

        frmListaCliente.setTitle("Listado de Clientes");
        frmListaCliente.setVisible(true);

        jToolBar2.setRollover(true);

        jLabel6.setText("Busqueda:");
        jToolBar2.add(jLabel6);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jToolBar2.add(jTextField3);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/find.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel.png"))); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout frmListaClienteLayout = new javax.swing.GroupLayout(frmListaCliente.getContentPane());
        frmListaCliente.getContentPane().setLayout(frmListaClienteLayout);
        frmListaClienteLayout.setHorizontalGroup(
            frmListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
            .addGroup(frmListaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        frmListaClienteLayout.setVerticalGroup(
            frmListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmListaClienteLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        frmRegistroCliente.setClosable(true);
        frmRegistroCliente.setTitle("Registro de clientes");
        frmRegistroCliente.setVisible(true);
        frmRegistroCliente.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Documento de Identidad:");
        frmRegistroCliente.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        frmRegistroCliente.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 144, -1));

        jLabel2.setText("Nombre:");
        frmRegistroCliente.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));
        frmRegistroCliente.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 143, -1));

        jLabel3.setText("Genero:");
        frmRegistroCliente.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel4.setText("Año de Nacimiento:");
        frmRegistroCliente.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel5.setText("Nacionalidad:");
        frmRegistroCliente.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peruano", "Argentino", "Colombiano", "Chileno", "Venezolano", "Brasileño", "Ecuatoriano" }));
        frmRegistroCliente.getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 145, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        frmRegistroCliente.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 145, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otros", " " }));
        frmRegistroCliente.getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 144, -1));

        jToolBar1.setRollover(true);

        btnGuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/database_save.png"))); // NOI18N
        btnGuardarCliente.setText("Guardar");
        btnGuardarCliente.setFocusable(false);
        btnGuardarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGuardarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGuardarCliente);

        btnCerrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cancel.png"))); // NOI18N
        btnCerrarCliente.setText("Cancelar");
        btnCerrarCliente.setFocusable(false);
        btnCerrarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCerrarCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCerrarCliente);

        frmRegistroCliente.getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 30));

        frmListaLicenciaConducir.setVisible(true);

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");

        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout frmListaLicenciaConducirLayout = new javax.swing.GroupLayout(frmListaLicenciaConducir.getContentPane());
        frmListaLicenciaConducir.getContentPane().setLayout(frmListaLicenciaConducirLayout);
        frmListaLicenciaConducirLayout.setHorizontalGroup(
            frmListaLicenciaConducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmListaLicenciaConducirLayout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(0, 244, Short.MAX_VALUE))
            .addGroup(frmListaLicenciaConducirLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmListaLicenciaConducirLayout.setVerticalGroup(
            frmListaLicenciaConducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmListaLicenciaConducirLayout.createSequentialGroup()
                .addGroup(frmListaLicenciaConducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(0, 252, Short.MAX_VALUE))
        );

        frmRegistroLicenciaConducir.setVisible(true);

        javax.swing.GroupLayout frmRegistroLicenciaConducirLayout = new javax.swing.GroupLayout(frmRegistroLicenciaConducir.getContentPane());
        frmRegistroLicenciaConducir.getContentPane().setLayout(frmRegistroLicenciaConducirLayout);
        frmRegistroLicenciaConducirLayout.setHorizontalGroup(
            frmRegistroLicenciaConducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frmRegistroLicenciaConducirLayout.setVerticalGroup(
            frmRegistroLicenciaConducirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        frmListaMetodoPago.setVisible(true);

        javax.swing.GroupLayout frmListaMetodoPagoLayout = new javax.swing.GroupLayout(frmListaMetodoPago.getContentPane());
        frmListaMetodoPago.getContentPane().setLayout(frmListaMetodoPagoLayout);
        frmListaMetodoPagoLayout.setHorizontalGroup(
            frmListaMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frmListaMetodoPagoLayout.setVerticalGroup(
            frmListaMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        frmRegistroMetodoPago.setVisible(true);

        javax.swing.GroupLayout frmRegistroMetodoPagoLayout = new javax.swing.GroupLayout(frmRegistroMetodoPago.getContentPane());
        frmRegistroMetodoPago.getContentPane().setLayout(frmRegistroMetodoPagoLayout);
        frmRegistroMetodoPagoLayout.setHorizontalGroup(
            frmRegistroMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frmRegistroMetodoPagoLayout.setVerticalGroup(
            frmRegistroMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        frmListaTarifa.setVisible(true);

        javax.swing.GroupLayout frmListaTarifaLayout = new javax.swing.GroupLayout(frmListaTarifa.getContentPane());
        frmListaTarifa.getContentPane().setLayout(frmListaTarifaLayout);
        frmListaTarifaLayout.setHorizontalGroup(
            frmListaTarifaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frmListaTarifaLayout.setVerticalGroup(
            frmListaTarifaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        frmRegistroTarifa.setVisible(true);

        javax.swing.GroupLayout frmRegistroTarifaLayout = new javax.swing.GroupLayout(frmRegistroTarifa.getContentPane());
        frmRegistroTarifa.getContentPane().setLayout(frmRegistroTarifaLayout);
        frmRegistroTarifaLayout.setHorizontalGroup(
            frmRegistroTarifaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frmRegistroTarifaLayout.setVerticalGroup(
            frmRegistroTarifaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        frmListaVehiculo.setVisible(true);

        javax.swing.GroupLayout frmListaVehiculoLayout = new javax.swing.GroupLayout(frmListaVehiculo.getContentPane());
        frmListaVehiculo.getContentPane().setLayout(frmListaVehiculoLayout);
        frmListaVehiculoLayout.setHorizontalGroup(
            frmListaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        frmListaVehiculoLayout.setVerticalGroup(
            frmListaVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        frmRegistroVehiculo.setVisible(true);

        javax.swing.GroupLayout frmRegistroVehiculoLayout = new javax.swing.GroupLayout(frmRegistroVehiculo.getContentPane());
        frmRegistroVehiculo.getContentPane().setLayout(frmRegistroVehiculoLayout);
        frmRegistroVehiculoLayout.setHorizontalGroup(
            frmRegistroVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        frmRegistroVehiculoLayout.setVerticalGroup(
            frmRegistroVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Mantenimiento");

        mnuCliente.setText("Cliente");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        jMenu3.add(mnuCliente);

        mnuLicenciaConducir.setText("Licencia de Conducir");
        mnuLicenciaConducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLicenciaConducirActionPerformed(evt);
            }
        });
        jMenu3.add(mnuLicenciaConducir);

        mnuMetodoPago.setText("Metodo de Pago");
        mnuMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMetodoPagoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMetodoPago);

        mnuTarifa.setText("Tarifa");
        mnuTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTarifaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuTarifa);

        mnuVehiculo.setText("Vehiculo");
        mnuVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVehiculoActionPerformed(evt);
            }
        });
        jMenu3.add(mnuVehiculo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
        this.jDesktopPane1.add(this.frmRegistroCliente);
        this.frmRegistroCliente.setSize(new Dimension (400,400));
        this.frmRegistroCliente.setVisible(true);
    }//GEN-LAST:event_mnuClienteActionPerformed

    private void mnuLicenciaConducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLicenciaConducirActionPerformed
        this.jDesktopPane1.add(this.frmRegistroLicenciaConducir);
        this.frmRegistroLicenciaConducir.setSize(new Dimension (400,400));
        this.frmRegistroLicenciaConducir.setVisible(true);
    }//GEN-LAST:event_mnuLicenciaConducirActionPerformed

    private void mnuMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMetodoPagoActionPerformed
        this.jDesktopPane1.add(this.frmRegistroMetodoPago);
        this.frmRegistroMetodoPago.setSize(new Dimension (400,400));
        this.frmRegistroMetodoPago.setVisible(true);
    }//GEN-LAST:event_mnuMetodoPagoActionPerformed

    private void mnuTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTarifaActionPerformed
        this.jDesktopPane1.add(this.frmRegistroTarifa);
        this.frmRegistroTarifa.setSize(new Dimension (400,400));
        this.frmRegistroTarifa.setVisible(true);
    }//GEN-LAST:event_mnuTarifaActionPerformed

    private void mnuVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVehiculoActionPerformed
        this.jDesktopPane1.add(this.frmRegistroVehiculo);
        this.frmRegistroVehiculo.setSize(new Dimension (400,400));
        this.frmRegistroVehiculo.setVisible(true);
    }//GEN-LAST:event_mnuVehiculoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClienteActionPerformed
        
    }//GEN-LAST:event_btnGuardarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRentaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRentaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRentaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRentaCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuRentaCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarCliente;
    private javax.swing.JButton btnGuardarCliente;
    private javax.swing.JInternalFrame frmListaCliente;
    private javax.swing.JInternalFrame frmListaLicenciaConducir;
    private javax.swing.JInternalFrame frmListaMetodoPago;
    private javax.swing.JInternalFrame frmListaTarifa;
    private javax.swing.JInternalFrame frmListaVehiculo;
    private javax.swing.JInternalFrame frmRegistroCliente;
    private javax.swing.JInternalFrame frmRegistroLicenciaConducir;
    private javax.swing.JInternalFrame frmRegistroMetodoPago;
    private javax.swing.JInternalFrame frmRegistroTarifa;
    private javax.swing.JInternalFrame frmRegistroVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuLicenciaConducir;
    private javax.swing.JMenuItem mnuMetodoPago;
    private javax.swing.JMenuItem mnuTarifa;
    private javax.swing.JMenuItem mnuVehiculo;
    // End of variables declaration//GEN-END:variables
}
